DICT_DIR = "dictionaries"

DICT_NOUNS = "english-nouns.txt"
DICT_ADJECTIVES = "english-adjectives.txt"
DICT_PROFANITIES = "bad-words.txt"

PASS_DEFAULT_LENGTH = 40
PASS_DEFAULT_ADDCHARS = 2
PASS_DEFAULT_WORD_LENGTH = 38
PASS_PROFANE = False
PASS_DEFAULT_DICT = DICT_NOUNS
